package model;

public enum Neighborhood {
	
    ALTOS_DE_PINHEIROS("Altos de Pinheiros"),
    ASSENTAMENTO_BELA_VISTA_DO_CHIBARRO("Assentamento Bela Vista do Chibarro"),
    CAMPUS_VILLE("Campus Ville"),
    CHACARA_D_ONOFRE("Chácara D'Onofre"),
    CHACARA_FLORA("Chácara Flora"),
    CHACARAS_VELOSA("Chácaras Velosa"),
    CIDADE_JARDIM("Cidade Jardim"),
    CONDOMINIO_SATELITE("Condomínio Satélite"),
    DISTRITO_INDUSTRIAL_I("Distrito Industrial I"),
    DISTRITO_INDUSTRIAL_II("Distrito Industrial II"),
    DISTRITO_INDUSTRIAL_III("Distrito Industrial III"),
    ESTACAO_DO_OURO("Estação do Ouro"),
    ESTACAO_TUTOIA("Estação Tutóia"),
    JARDIM_ACLIMACAO("Jardim Aclimação"),
    JARDIM_ADALBERTO_DE_OLIVEIRA_ROXO("Jardim Adalberto de Oliveira Roxo"),
    JARDIM_AMERICA("Jardim América"),
    JARDIM_ARANGA("Jardim Aranga"),
    JARDIM_ARARAQUARA("Jardim Araraquara"),
    JARDIM_ARCO_IRIS("Jardim Arco-Íris"),
    JARDIM_AGUAS_DO_PAIOL("Jardim Águas do Paiol"),
    JARDIM_ARTICO("Jardim Ártico"),
    JARDIM_BOTANICO("Jardim Botânico"),
    JARDIM_BRASIL("Jardim Brasil"),
    JARDIM_BRASILIA("Jardim Brasília"),
    JARDIM_CRUZEIRO_DO_SUL("Jardim Cruzeiro do Sul"),
    JARDIM_DEL_REY("Jardim Del Rey"),
    JARDIM_DOM_PEDRO_I("Jardim Dom Pedro I"),
    JARDIM_DOS_IPES("Jardim dos Ipês"),
    JARDIM_DOS_MANACAS("Jardim dos Manacás"),
    JARDIM_DUMONT("Jardim Dumont"),
    JARDIM_ELIANA("Jardim Eliana"),
    JARDIM_EUROPA("Jardim Europa"),
    JARDIM_FLORIDIANA("Jardim Floridiana"),
    JARDIM_GAIVOTAS("Jardim das Gaivotas"),
    JARDIM_HIGIENOPOLIS("Jardim Higienópolis"),
    JARDIM_HORTENSIAS("Jardim Hortênsias"),
    JARDIM_IMPERIAL("Jardim Imperial"),
    JARDIM_IMPERADOR("Jardim Imperador"),
    JARDIM_INDAIA("Jardim Indaiá"),
    JARDIM_ITALIA("Jardim Itália"),
    JARDIM_JOINVILLE("Jardim Joinville"),
    JARDIM_MARIA_LUIZA("Jardim Maria Luiza"),
    JARDIM_MARTINEZ("Jardim Martinez"),
    JARDIM_MORADA_DO_SOL("Jardim Morada do Sol"),
    JARDIM_MORUMBI("Jardim Morumbi"),
    JARDIM_NOVA_AMERICA("Jardim Nova América"),
    JARDIM_NOVA_EPOCA("Jardim Nova Época"),
    JARDIM_NOSSA_SENHORA_DO_CARMO("Jardim Nossa Senhora do Carmo"),
    JARDIM_PALMARES("Jardim Palmares"),
    JARDIM_PALMEIRAS("Jardim das Palmeiras"),
    JARDIM_PANORAMA("Jardim Panorama"),
    JARDIM_PARQUE_ANCHIETA("Jardim Parque Anchieta"),
    JARDIM_PINHEIROS("Jardim Pinheiros"),
    JARDIM_PRIMAVERA("Jardim Primavera"),
    JARDIM_QUITANDINHA("Jardim Quitandinha"),
    JARDIM_RAFAELA_AMOROSO_MICELLI("Jardim Rafaela Amoroso Micelli"),
    JARDIM_REGINA("Jardim Regina"),
    JARDIM_RESIDENCIAL_AGUA_BRANCA("Jardim Residencial Água Branca"),
    JARDIM_RESIDENCIAL_IEDA("Jardim Residencial Ieda"),
    JARDIM_RESIDENCIAL_LUPO("Jardim Residencial Lupo"),
    JARDIM_RESIDENCIAL_SANTA_MONICA("Jardim Residencial Santa Mônica"),
    JARDIM_ROBERTO_SELMI_DEI("Jardim Roberto Selmi Dei"),
    JARDIM_SANTA_ADELIA("Jardim Santa Adélia"),
    JARDIM_SANTA_ANGELINA("Jardim Santa Angelina"),
    JARDIM_SANTA_CLARA("Jardim Santa Clara"),
    JARDIM_SANTA_JULIA("Jardim Santa Júlia"),
    JARDIM_SANTA_LUCIA("Jardim Santa Lúcia"),
    JARDIM_SANTA_MARTA("Jardim Santa Marta"),
    JARDIM_SANTA_RITA_DE_CASSIA("Jardim Santa Rita de Cássia"),
    JARDIM_SANTO_ANTONIO("Jardim Santo Antônio"),
    JARDIM_SAO_RAFAEL("Jardim São Rafael"),
    JARDIM_SILVANIA("Jardim Silvânia"),
    JARDIM_SILVESTRE("Jardim Silvestre"),
    JARDIM_TAMOIO("Jardim Tamoio"),
    JARDIM_TANGARA("Jardim Tangará"),
    JARDIM_UNIVERSAL("Jardim Universal"),
    JARDIM_VALE_DAS_ROSAS("Jardim Vale das Rosas"),
    JARDIM_VENEZA("Jardim Veneza"),
    JARDIM_VIADUTO("Jardim Viaduto"),
    JARDIM_VITORIA("Jardim Vitória"),
    PARQUE_CECAP("Parque Cecap"),
    PARQUE_DAS_ARVORES("Parque das Árvores"),
    PARQUE_GRAMADO("Parque Gramado"),
    PARQUE_IGACABA("Parque Igaçaba"),
    PARQUE_IGUATEMI("Parque Iguatemi"),
    PARQUE_LARANJEIRAS("Parque Laranjeiras"),
    PARQUE_PLANALTO("Parque Planalto"),
    PARQUE_RESIDENCIAL_JATOBA("Parque Residencial Jatobá"),
    PARQUE_RESIDENCIAL_LAURA_MOLINA("Parque Residencial Laura Molina"),
    PARQUE_RESIDENCIAL_SAO_PAULO("Parque Residencial São Paulo"),
    PARQUE_SAO_JOSE("Parque São José"),
    PARQUE_VALE_DO_SOL("Parque Vale do Sol"),
    PARQUE_DOS_SABIAS("Parque dos Sabiás"),
    RECANTO_DOS_NOBRES("Recanto dos Nobres"),
    RECREIO_CAMPESTRE_IDANORMA("Recreio Campestre Idanorma"),
    RESIDENCIAL_ACAPULCO("Residencial Acapulco"),
    RESIDENCIAL_ALAMEDAS("Residencial Alamedas"),
    RESIDENCIAL_PARAISO("Residencial Paraíso"),
    SANTA_LUZIA("Santa Luzia"),
    SANTANA("Santana"),
    SAO_GERALDO("São Geraldo"),
    VALLE_VERDE("Valle Verde"),
    VICTORIO_DE_SANTI("Victório de Santi"),
    VILA_BELA_VISTA("Vila Bela Vista"),
    VILA_BIAGIONI("Vila Biagioni"),
    VILA_CIDADE_INDUSTRIAL("Vila Cidade Industrial"),
    VILA_ESPERANCA("Vila Esperança"),
    VILA_FERROVIARIA("Vila Ferroviária"),
    VILA_FREITAS("Vila Freitas"),
    VILA_FURLAN("Vila Furlan"),
    VILA_GASPAR("Vila Gaspar"),
    VILA_GIRASSOL("Vila Girassol"),
    VILA_GUAIANASES("Vila Guaianases"),
    VILA_HARMONIA("Vila Harmonia"),
    VILA_INDEPENDENCIA("Vila Independência"),
    VILA_JOINVILLE("Vila Joinville"),
    VILA_MELHADO("Vila Melhado"),
    VILA_NOSSA_SENHORA_APARECIDA("Vila Nossa Senhora Aparecida"),
    VILA_ORIENTE("Vila Oriente"),
    VILA_RENATA("Vila Renata"),
    VILA_SANTA_MARIA("Vila Santa Maria"),
    VILA_SANTO_MALARA("Vila Santo Malara"),
    VILA_SEDENHO("Vila Sedenho"),
    VILA_SERVIDOR("Vila do Servidor"),
    VILA_SUCONASA("Vila Suconasa"),
    VILA_VELOSA("Vila Velosa"),
    VILA_VIEIRA("Vila Vieira"),
    VILA_XAVIER("Vila Xavier");
	
	private String description;
	
	Neighborhood(String description) {
		this.description = description;
	}
		
	public String getDescription() {
		return description;
	}
}
